--require('lint').linters.qmllint = {
--  cmd = 'qmllint',
--  stdin = false, -- or false if it doesn't support content input via stdin. In that case the filename is automatically added to the arguments.
--  stream = "stderr", -- ('stdout' | 'stderr' | 'both') configure the stream to which the linter outputs the linting result.
--  ignore_exitcode = true, -- set this to true if the linter exits with a code != 0 and that's considered normal.
--  parser = require('lint.parser').from_errorformat('f:%l : %m', {source = "qmllint"} )
--}
--require('lint').linters_by_ft = {
--    qml = {"qmllint",},
--    json = {"jsonlint",}
--}
--vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--  callback = function()
--    require("lint").try_lint()
--  end,
--})
